export const CART_ACTION_TYPES = {
  FETCH_CART_INIT: 'FETCH_CART_INIT',
  FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS',
  FETCH_CART_FAILED: 'FETCH_CART_FAILED',
  SET_IS_CART_OPEN: 'SET_IS_CART_OPEN',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  SET_CART_STATE: 'SET_CART_STATE'
};

export const PRODUCT_ACTION_TYPES = {
  FETCH_PRODUCTS_INIT: 'FETCH_PRODUCTS_INIT',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILED: 'FETCH_PRODUCTS_FAILED'
};

export const createAction = (type, payload) => ({ type, payload });
